# Generated by Django 5.2.7 on 2025-12-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='title',
            field=models.CharField(default=''),
        ),
    ]
